name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - development
  push:
    branches:
      - development

jobs:
  main:
    runs-on: ubuntu-latest
    container: openmc/openmc:latest

    steps:
      - uses: actions/checkout@v2

      - name: Apt dependencies
        shell: bash
        run: |
          apt -y update
          apt install -y python3-venv
          python -m venv venv
          source venv/bin/activate

      - name: Install
        shell: bash
        run: |
          pip install -U pip
          pushd /root/OpenMC/openmc
          pip install .[test]
          popd
          pip install .[test]

      - name: Test
        shell: bash
        run: pytest tests
